// automatically generated by the FlatBuffers compiler, do not modify
package org.apache.spark.network.rpmof;

import java.nio.*;
import java.lang.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BlockMetadata extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BlockMetadata __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int shuffleId() { return bb.getShort(bb_pos + 0) & 0xFFFF; }
  public int mapId() { return bb.getShort(bb_pos + 2) & 0xFFFF; }
  public int reduceId() { return bb.getShort(bb_pos + 4) & 0xFFFF; }
  public long buffer() { return bb.getLong(bb_pos + 8); }
  public long size() { return bb.getLong(bb_pos + 16); }
  public long rkey() { return bb.getLong(bb_pos + 24); }

  public static int createBlockMetadata(FlatBufferBuilder builder, int shuffleId, int mapId, int reduceId, long buffer, long size, long rkey) {
    builder.prep(8, 32);
    builder.putLong(rkey);
    builder.putLong(size);
    builder.putLong(buffer);
    builder.pad(2);
    builder.putShort((short)reduceId);
    builder.putShort((short)mapId);
    builder.putShort((short)shuffleId);
    return builder.offset();
  }
}

