// automatically generated by the FlatBuffers compiler, do not modify
package org.apache.spark.network.rpmof;

import java.nio.*;
import java.lang.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BlockMetadataMsg extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static BlockMetadataMsg getRootAsBlockMetadataMsg(ByteBuffer _bb) { return getRootAsBlockMetadataMsg(_bb, new BlockMetadataMsg()); }
  public static BlockMetadataMsg getRootAsBlockMetadataMsg(ByteBuffer _bb, BlockMetadataMsg obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BlockMetadataMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public BlockMetadata blockMetadata(int j) { return blockMetadata(new BlockMetadata(), j); }
  public BlockMetadata blockMetadata(BlockMetadata obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 32, bb) : null; }
  public int blockMetadataLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createBlockMetadataMsg(FlatBufferBuilder builder,
      int blockMetadataOffset) {
    builder.startTable(1);
    BlockMetadataMsg.addBlockMetadata(builder, blockMetadataOffset);
    return BlockMetadataMsg.endBlockMetadataMsg(builder);
  }

  public static void startBlockMetadataMsg(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addBlockMetadata(FlatBufferBuilder builder, int blockMetadataOffset) { builder.addOffset(0, blockMetadataOffset, 0); }
  public static void startBlockMetadataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(32, numElems, 8); }
  public static int endBlockMetadataMsg(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
}

