// automatically generated by the FlatBuffers compiler, do not modify
package org.apache.spark.network.rpmof;

import java.nio.*;
import java.lang.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GetBlockMetadataMsg extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static GetBlockMetadataMsg getRootAsGetBlockMetadataMsg(ByteBuffer _bb) { return getRootAsGetBlockMetadataMsg(_bb, new GetBlockMetadataMsg()); }
  public static GetBlockMetadataMsg getRootAsGetBlockMetadataMsg(ByteBuffer _bb, GetBlockMetadataMsg obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetBlockMetadataMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int shuffleId() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int startPartition() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int endPartition() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }

  public static int createGetBlockMetadataMsg(FlatBufferBuilder builder,
      int shuffleId,
      int startPartition,
      int endPartition) {
    builder.startTable(3);
    GetBlockMetadataMsg.addEndPartition(builder, endPartition);
    GetBlockMetadataMsg.addStartPartition(builder, startPartition);
    GetBlockMetadataMsg.addShuffleId(builder, shuffleId);
    return GetBlockMetadataMsg.endGetBlockMetadataMsg(builder);
  }

  public static void startGetBlockMetadataMsg(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addShuffleId(FlatBufferBuilder builder, int shuffleId) { builder.addShort(0, (short)shuffleId, (short)0); }
  public static void addStartPartition(FlatBufferBuilder builder, int startPartition) { builder.addShort(1, (short)startPartition, (short)0); }
  public static void addEndPartition(FlatBufferBuilder builder, int endPartition) { builder.addShort(2, (short)endPartition, (short)0); }
  public static int endGetBlockMetadataMsg(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
}

